name: jaspr_bloc
description: Jaspr components that make it easy to implement the BLoC (Business
  Logic Component) design pattern. Built to be used with the bloc state
  management package.
version: 0.0.1
repository: https://github.com/f-person/jaspr_bloc
issue_tracker: https://github.com/f-person/jaspr_bloc

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  bloc: ^8.1.0
  jaspr: ^0.11.1
  jaspr_provider :
    git : 
      url : https://github.com/lonshanworld/jaspr_provider_ls.git
      ref : main

dev_dependencies:
  jaspr_test: ^0.11.1
  webdev: ^2.7.12
